apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: hercules
spec:
  
  shortDescription: Scans your clusters for potential resource issues
  version: {{ .TagName }}
  description: |
    Hercules is a utility that scans live Kubernetes clusters and reports
    potential issues with deployed resources and configurations.
    It sanitizes your cluster based on what's deployed and not what's
    sitting on disk. By scanning your cluster, it detects misconfigurations
    and ensure best practices are in place thus preventing potential future
    headaches. It aims at reducing the cognitive overload one faces when
    operating a Kubernetes cluster in the wild. Furthermore, if your
    cluster employs a metric-server, it reports potential resources
    over/under allocations and attempts to warn you should your cluster
    run out of capacity.

    Hercules is a readonly tool, it does not alter any of your Kubernetes
    resources in any way!
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{ addURIAndSha "https://github.com/un/hercules/releases/download/{{ .TagName }}/Darwin_x86_64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-hercules
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{ addURIAndSha "https://github.com/unknown/hercules/releases/download/{{ .TagName }}/_Linux_x86_64.tar.gz" .TagName }}
      bin: kubectl-hercules
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{ addURIAndSha "https://github.com/unknown/hercules/releases/download/{{ .TagName }}/_Windows_x86_64.tar.gz" .TagName }}
      bin: kubectl-hercules.exe